defaultDocument implementation
cloudflare/kv-asset-handler pull request #161
Opened 2020-12-15 01:50 UTC by boemekeld

Hey guys,

In some cases, "index.html" is not the default document.
I work on some projects that are being migrated to Edge and that use "index.shtm" for example.
For this, I suggest the inclusion of an option **defaultDocument**.

Thanks. 👍

2020-12-15 05:27 UTC, SukkaW requested changes

2020-12-15 05:27 UTC, SukkaW commented on .gitignore
> -dist
Why remove `dist` from `.gitignore`?

2020-12-15 05:31 UTC, SukkaW commented
> I work on some projects that are being migrated to Edge and that use "index.shtm" for example.

`shtml` is not "static HTML". It is "server-side HTML" which means the served file is generated dynamically.

2020-12-15 08:46 UTC, boemekeld commented on .gitignore
> -dist
Hi @SukkaW, my mistake. Was solved. Thanks.

2020-12-15 08:58 UTC, boemekeld commented
> website

I am building a platform that can host different stacks, including websites with SSI (Server Side Includes).

There are a number of reasons that do not allow me to rename the files to .HTML, like as SEO, compatibility with other environments, etc.

In this necenary, SHTML files are previously generated in the build stage, so they are static files.

I appreciate your comment. Thanks.

2020-12-18 04:41 UTC, boemekeld commented
Hi @SukkaW

Could you review this pull request?

Thanks.

2021-01-06 23:21 UTC, boemekeld commented
Up

2021-05-20 18:20 UTC, boemekeld commented
@signalnerve of course! I will do this soon.

2021-05-20 23:28 UTC, boemekeld commented
@signalnerve done!

2021-05-21 17:30 UTC, Cherry commented
Thanks, this looks like a good change and should close #87.

@boemekeld Could you add a test for this new functionality for `mapRequestToAsset` in `src/test/mapRequestToAsset.ts`?

2021-05-21 17:47 UTC, boemekeld commented
@Cherry yes, let me check it.

2021-05-21 19:20 UTC, boemekeld commented
@Cherry done!

2021-05-21 19:53 UTC, signalnerve commented
> @Cherry done!

we're going to work on supporting running our test workflow on pull requests, but in the meantime, can you post your test output here just so I have a paper trail before merge? ty!

2021-05-21 20:03 UTC, boemekeld commented
@signalnerve sure.

> @cloudflare/kv-asset-handler@0.1.1 pretest C:\git\bohr-cloud\kv-asset-handler
> npm run build

> @cloudflare/kv-asset-handler@0.1.1 build C:\git\bohr-cloud\kv-asset-handler
> tsc -d

> @cloudflare/kv-asset-handler@0.1.1 test C:\git\bohr-cloud\kv-asset-handler
> ava dist/test/*.js --verbose

  - getAssetFromKV » getAssetFromKV when body not empty, should invoke .cancel()
  √ mapRequestToAsset » mapRequestToAsset() correctly changes /about -> /about/index.html
  √ mapRequestToAsset » mapRequestToAsset() correctly changes /about/ -> /about/index.html
  √ mapRequestToAsset » mapRequestToAsset() correctly changes /about.me/ -> /about.me/index.html
  √ mapRequestToAsset » mapRequestToAsset() correctly changes /about -> /about/default.html
  √ serveSinglePageApp » serveSinglePageApp returns root asset path when request path ends in .html
  √ serveSinglePageApp » serveSinglePageApp returns root asset path when request path does not have extension
  √ serveSinglePageApp » serveSinglePageApp returns requested asset when request path has non-html extension
Environment doesnt support readable streams
  √ getAssetFromKV » getAssetFromKV does not cache on Cloudflare when bypass cache set
Environment doesnt support readable streams
  √ getAssetFromKV » getAssetFromKV if not in asset manifest still returns nohash.txt
  √ getAssetFromKV » getAssetFromKV when setting browser caching
  √ getAssetFromKV » getAssetFromKV when namespace not bound fails
  √ getAssetFromKV » getAssetFromKV return correct val from KV and default caching
  √ getAssetFromKV » getAssetFromKV evaluated the file matching the extensionless path first /client/ -> client
  √ getAssetFromKV » getAssetFromKV evaluated the file matching the extensionless path first /client -> client
  √ getAssetFromKV » getAssetFromKV if no asset manifest /client -> client fails
  √ getAssetFromKV » getAssetFromKV if sub/ -> sub/index.html served
  √ getAssetFromKV » getAssetFromKV gets index.html by default for / requests
  √ getAssetFromKV » getAssetFromKV non ASCII path support
  √ getAssetFromKV » getAssetFromKV supports browser percent encoded URLs
  √ getAssetFromKV » getAssetFromKV supports user percent encoded URLs
  √ getAssetFromKV » getAssetFromKV custom key modifier
  √ getAssetFromKV » getAssetFromKV with no trailing slash on root
  √ getAssetFromKV » getAssetFromKV with no trailing slash on a subdirectory
  √ getAssetFromKV » getAssetFromKV no result throws an error
  √ getAssetFromKV » getAssetFromKV passing in a custom NAMESPACE serves correct asset
  √ getAssetFromKV » getAssetFromKV when setting custom cache setting
  √ getAssetFromKV » getAssetFromKV when custom namespace without the asset should fail
  √ getAssetFromKV » getAssetFromKV only decode URL when necessary
  √ getAssetFromKV » getAssetFromKV Support for user decode url path
  √ getAssetFromKV » getAssetFromKV when etag and if-none-match are present but if-none-match !== etag, should bypass cache
  √ getAssetFromKV » getAssetFromKV caches on two sequential requests
  √ getAssetFromKV » getAssetFromKV if-none-match not sent but resource in cache, should return hit
  √ getAssetFromKV » getAssetFromKV if range request submitted and resource in cache, request fulfilled
  √ getAssetFromKV » getAssetFromKV TTls set to null should not cache on browser or edge (111ms)
Environment doesnt support readable streams
Environment doesnt support readable streams
  √ getAssetFromKV » getAssetFromKV does not store max-age on two sequential requests (116ms)
  √ getAssetFromKV » getAssetFromKV when if-none-match === etag and etag === pathKey in manifest, should revalidate (108ms)
  ─

  36 tests passed
  1 test todo

2021-05-21 20:40 UTC, Cherry approved these changes
LGTM. Thanks for the contribution!

2021-05-21 21:02 UTC, merged